import { Type } from "@sinclair/typebox";
import Anthropic from "@anthropic-ai/sdk";
import { getConfig } from "../config.js";
import { searchMemoriesTool } from "./search-memories.js";
import { webSearchTool } from "./web-search.js";
import { rememberInsightTool } from "./remember-insight.js";

const SYSTEM_PROMPT = `You are Mosaic, an opinionated market intelligence agent. Your job is to cut through noise and deliver sharp strategic insight by combining your team's internal knowledge with current market signals.

When generating a report, always:
- Run 2-3 targeted mosaic_search_memories queries to surface internal context
- Run 2-3 mosaic_web_search queries to capture market trends and competitor moves
- Save 2-3 key non-obvious insights with mosaic_remember_insight so future reports are smarter
- Synthesize both into a structured, opinionated report

Output in this exact format:

# Market Report: [Topic]
_Generated by Mosaic_

## Executive Summary
2-3 sentences capturing the single most important insight.

## Market Trends
Current dynamics, growth signals, and emerging patterns from the web.

## Internal Context
What the team already knows — signals from Slack, emails, docs.

## Competitive Landscape
Key players, recent moves, differentiation opportunities.

## Recommendations
3 concrete, actionable next steps.

---
_Sources: [list sources used]_

Be specific, not generic. Surface the non-obvious. Skip filler. Do not add disclaimers about missing data.`;

// Internal tools used by the report generation loop
const INTERNAL_TOOLS = [searchMemoriesTool, webSearchTool, rememberInsightTool];

const ANTHROPIC_TOOL_DEFS: Anthropic.Tool[] = INTERNAL_TOOLS.map((t) => ({
  name: t.name,
  description: t.description,
  input_schema: {
    type: "object" as const,
    properties: Object.fromEntries(
      Object.entries((t.parameters as any).properties ?? {}).map(([k, v]: [string, any]) => [
        k,
        { type: v.type, description: v.description },
      ])
    ),
    required: Object.keys((t.parameters as any).properties ?? {}),
  },
}));

export const generateReportTool = {
  name: "mosaic_generate_report",
  label: "Generate Market Report",
  description:
    "Generate a full market intelligence report on a topic. Searches internal knowledge and the web, synthesizes findings, and saves key insights back to memory.",
  parameters: Type.Object({
    topic: Type.String({ description: "The topic, market, or product area to report on." }),
  }),
  async execute(_id: string, params: unknown) {
    const { topic } = params as { topic: string };
    const config = getConfig();
    const apiKey = config.anthropicApiKey ?? process.env.ANTHROPIC_API_KEY;

    if (!apiKey) {
      return {
        content: [
          {
            type: "text" as const,
            text: "Anthropic API key not configured. Set it in plugin config or ANTHROPIC_API_KEY env var.",
          },
        ],
      };
    }

    const anthropic = new Anthropic({ apiKey });
    const messages: Anthropic.MessageParam[] = [
      { role: "user", content: `Generate a market report on: ${topic}` },
    ];

    try {
      while (true) {
        const response = await anthropic.messages.create({
          model: "claude-opus-4-6",
          max_tokens: 4096,
          system: SYSTEM_PROMPT,
          tools: ANTHROPIC_TOOL_DEFS,
          messages,
        });

        if (response.stop_reason === "end_turn") {
          const textBlock = response.content.find((b) => b.type === "text");
          const text = textBlock ? (textBlock as Anthropic.TextBlock).text : "No report generated.";
          return { content: [{ type: "text" as const, text }] };
        }

        messages.push({ role: "assistant", content: response.content });
        const toolResults: Anthropic.ToolResultBlockParam[] = [];

        for (const block of response.content) {
          if (block.type !== "tool_use") continue;
          const tool = INTERNAL_TOOLS.find((t) => t.name === block.name);
          let resultText = "Tool not found.";
          if (tool) {
            const res = await tool.execute(block.id, block.input);
            resultText = res.content[0]?.text ?? "";
          }
          toolResults.push({ type: "tool_result", tool_use_id: block.id, content: resultText });
        }

        messages.push({ role: "user", content: toolResults });
      }
    } catch (e: any) {
      return {
        content: [{ type: "text" as const, text: `Report generation failed: ${e.message}` }],
      };
    }
  },
};
